### ISSUE TITLE
Numerous complaints about faucet being down

### ISSUE THREAD

**Issue by andygolay** [movementlabsxyz/M1#125]
Both faucet website and with CLI. 

Example output from CLI:

  ```
  $ movement aptos init
  Configuring for profile default
  Choose network from [devnet, testnet, mainnet, local, custom | defaults to devnet]
  testnet
  Enter your private key as a hex literal (0x...) [Current: None | No input: Generate new key (or keep one if present)]
  **
  Account * doesn't exist, creating it and funding it with 100000000 Octas
  res: Err(aptos error: "{\n  "Error": "API error: Faucet issue: FaucetClientError { inner: Inner { kind: HttpStatus(404), source: None } }"\n}")
  gitpod /workspace/movement-deploy (main)
```

**Comment by radupopa369** [comment]
according to our docs https://docs.movementlabs.xyz/ecosystem/faucet

the faucet for m1 cli is https://aptos.devnet.m1.movementlabs.xyz

**Comment by andygolay** [comment]
> according to our docs https://docs.movementlabs.xyz/ecosystem/faucet
> 
> the faucet for m1 cli is https://aptos.devnet.m1.movementlabs.xyz

Okay I checked this and yes it worked. Seems like the user-reported error was caused by user error such as perhaps an incorrect RPC url.

It looks like specifically M2 and MEVM faucets are not working from the faucet website.

@tonyxia2023 did you happen to make any changes to M2 or MEVM which are affecting the faucet?
